export const testIDs = {
  ONBOARDING: {
    SCREEN: 'ONBOARDING_SCREEN',
    WHAT_BUTTON: 'WHAT_BUTTON',
    WHERE_BUTTON: 'WHERE_BUTTON',
    HOW_BUTTON: 'HOW_BUTTON',
    LOG_IN_BUTTON: 'LOG_IN_BUTTON',
  },
  PRIVACY: {
    SCREEN: 'PRIVACY_SCREEN',
    PRIVACY_ACCEPT_BUTTON: 'PRIVACY_ACCEPT_BUTTON',
  },
  WELCOME: {
    SCREEN: 'WELCOME_SCREEN',
    START_BUTTON: 'START_BUTTON',
  },
  QUESTION: {
    SCREEN: 'QUESTION_SCREEN',
    YES_BUTTON: 'YES_BUTTON',
    NO_BUTTON: 'NO_BUTTON',
    NEXT_QUESTION_BUTTON: 'NEXT_QUESTION_BUTTON',
    MULTIPLE_CHOICE_OPTION: 'MULTIPLE_CHOICE_OPTION',
    PICKER_DAY: 'PICKER_DAY',
    PICKER_MONTH: 'PICKER_MONTH',
    PICKER_YEAR: 'PICKER_YEAR',
  },
  GO_BACK_SCREEN: {
    SCREEN: 'GO_BACK_SCREEN',
    GO_BACK_BUTTON: 'GO_BACK_BUTTON',
  },
  IMPORT_DATA: {
    SCREEN: 'IMPORT_DATA_SCREEN',
  },
  NAVIGATION: {
    HEADER_BACK_BUTTON: 'HEADER_BACK_BUTTON',
  },
  NOTIFICATON: {
    SCREEN: 'NOTIFICATION_SCREEN',
    SKIP_BUTTON: 'SKIP_BUTTON',
    ACCEPT_BUTTON: 'ACCEPT_BUTTON',
  },
  LIFE_EVENTS: {
    SCREEN: 'LIFE_EVENTS_SCREEN',
    LIFE_EVENT_CARD: 'LIFE_EVENT_CARD',
    ANIMATED_VIEW: 'ANIMATED_VIEW',
  },
  ACCOUNT: {
    SCREEN: 'ACCOUNT_SCREEN',
    TAB_BUTTON: 'ACCOUNT_TAB_BUTTON',
    EXPORT_DATA_BUTTON: 'EXPORT_DATA_BUTTON',
    VIEW_PRIVACY_BUTTON: 'VIEW_PRIVACY_BUTTON',
    DELETE_DATA_BLOCK_BUTTON: 'DELETE_DATA_BLOCK_BUTTON',
  },
  DELETE_DATA: {
    SCREEN: 'DELETE_DATA_SCREEN',
    MODAL: 'DELETE_DATA_MODAL',
    DELETE_BUTTON: 'DELETE_DATA_BUTTON',
    DELETE_DATA_MODAL_BUTTON: 'DELETE_DATA_MODAL_BUTTON',
  },
};
