export const testIDs = {
  ONBOARDING: {
    SCREEN: 'ONBOARDING_SCREEN',
    WHAT_BUTTON: 'WHAT_BUTTON',
    WHERE_BUTTON: 'WHERE_BUTTON',
    HOW_BUTTON: 'HOW_BUTTON',
    LOG_IN_BUTTON: 'LOG_IN_BUTTON',
  },
  PRIVACY: {
    SCREEN: 'PRIVACY_SCREEN',
    PRIVACY_ACCEPT_BUTTON: 'PRIVACY_ACCEPT_BUTTON',
  },
  WELCOME: {
    SCREEN: 'WELCOME_SCREEN',
    START_BUTTON: 'START_BUTTON',
  },
  QUESTION: {
    SCREEN: 'QUESTION_SCREEN',
    YES_BUTTON: 'YES_BUTTON',
    NO_BUTTON: 'NO_BUTTON',
    NEXT_QUESTION_BUTTON: 'NEXT_QUESTION_BUTTON',
  },
  IMPORT_DATA: {
    SCREEN: 'IMPORT_DATA_SCREEN',
  },
  NAVIGATION: {
    HEADER_BACK_BUTTON: 'HEADER_BACK_BUTTON',
  },
};
